"""Pure CameraChannel model for Parcel K5 (Sol lane).

D455-like intrinsics, 35 cm Go2 mount geometry, and RGB/depth/seg frame
envelopes. No EGL / MuJoCo — Opus backs ``CameraBackend`` in sim.
"""

from __future__ import annotations

from parcel_robot.camera_channel.channel import (
    CameraBackend,
    CameraChannel,
    CameraChannelSpec,
    assert_nominal_d455_contract,
)
from parcel_robot.camera_channel.d455 import (
    BASE_FRAME_ID,
    CALIBRATION_ID_NOMINAL,
    CAMERA_COLOR_FRAME_ID,
    CAMERA_DEPTH_FRAME_ID,
    CAMERA_SEG_FRAME_ID,
    D455_CX_PX,
    D455_CY_PX,
    D455_DEPTH_FPS,
    D455_DEPTH_MAX_M,
    D455_DEPTH_MIN_M,
    D455_FX_PX,
    D455_FY_PX,
    D455_HEIGHT_PX,
    D455_RGB_FPS,
    D455_WIDTH_PX,
    MOUNT_FORWARD_OFFSET_M,
    MOUNT_HEIGHT_M,
    MOUNT_LATERAL_OFFSET_M,
    MOUNT_PITCH_UP_RAD,
    MOUNT_ROLL_RAD,
    MOUNT_YAW_RAD,
    CameraIntrinsics,
    CameraMountGeometry,
    d455_color_intrinsics,
    go2_d455_mount,
)
from parcel_robot.camera_channel.frames import (
    FRAME_KINDS,
    CameraFrameEnvelope,
    ColorFrameMeta,
    DepthFrameMeta,
    FrameKind,
    SegFrameMeta,
    color_meta_from_mapping,
    default_color_meta,
)

__all__ = [
    "BASE_FRAME_ID",
    "CALIBRATION_ID_NOMINAL",
    "CAMERA_COLOR_FRAME_ID",
    "CAMERA_DEPTH_FRAME_ID",
    "CAMERA_SEG_FRAME_ID",
    "CameraBackend",
    "CameraChannel",
    "CameraChannelSpec",
    "CameraFrameEnvelope",
    "CameraIntrinsics",
    "CameraMountGeometry",
    "ColorFrameMeta",
    "D455_CX_PX",
    "D455_CY_PX",
    "D455_DEPTH_FPS",
    "D455_DEPTH_MAX_M",
    "D455_DEPTH_MIN_M",
    "D455_FX_PX",
    "D455_FY_PX",
    "D455_HEIGHT_PX",
    "D455_RGB_FPS",
    "D455_WIDTH_PX",
    "DepthFrameMeta",
    "FRAME_KINDS",
    "FrameKind",
    "MOUNT_FORWARD_OFFSET_M",
    "MOUNT_HEIGHT_M",
    "MOUNT_LATERAL_OFFSET_M",
    "MOUNT_PITCH_UP_RAD",
    "MOUNT_ROLL_RAD",
    "MOUNT_YAW_RAD",
    "SegFrameMeta",
    "assert_nominal_d455_contract",
    "color_meta_from_mapping",
    "d455_color_intrinsics",
    "default_color_meta",
    "go2_d455_mount",
]
