"""Typed, deterministic contracts between Parcel's language and control planes.

The package deliberately contains no simulator, controller, or model I/O.  A
language model may propose a :class:`PlanIR`, but only the validator and task
executive can admit it for later dispatch through runtime-owned adapters.
"""

from .compiler import (
    compile_plan_contracts,
    compile_plan_sketch,
    materialize_planner_output,
)
from .contracts import (
    AffectEvidence,
    BatteryStateSnapshot,
    ExecutionResult,
    FrozenDict,
    GoalSpec,
    GoalTarget,
    IntentFrame,
    ObservationSnapshot,
    ObservedEntity,
    PlanIR,
    PlanStep,
    ResourceLease,
    RobotStateSnapshot,
    SafetyStateSnapshot,
    SensorSnapshot,
    SuccessCondition,
    TaskStateSnapshot,
    VerifiedFact,
)
from .executive import (
    DispatchRequest,
    ExecutiveSubmission,
    InterruptDecision,
    InterruptRequest,
    ReportDisposition,
    ResourceLocks,
    TaskExecutive,
)
from .plan_sketch import (
    NavigationGrounding,
    PlanSketch,
    PlanSketchGoal,
    PlanSketchStep,
)
from .router import DeterministicIntentRouter
from .runtime_adapter import (
    ActiveSemanticDispatch,
    DispatchKey,
    SemanticRuntimeState,
    SemanticTaskRuntimeAdapter,
    admitted_plan_schema,
    admitted_plan_sketch_schema,
    bind_plan_context,
    contextual_plan_schema,
    contextual_planner_schema,
    dispatch_key,
    planner_output_contract,
)
from .validator import (
    PlanValidationError,
    PlanValidator,
    SkillContract,
    SkillContractRegistry,
    ValidatedPlan,
    ValidatedStep,
)

__all__ = [
    "ActiveSemanticDispatch",
    "AffectEvidence",
    "BatteryStateSnapshot",
    "DeterministicIntentRouter",
    "DispatchKey",
    "DispatchRequest",
    "ExecutionResult",
    "ExecutiveSubmission",
    "FrozenDict",
    "GoalSpec",
    "GoalTarget",
    "IntentFrame",
    "InterruptDecision",
    "InterruptRequest",
    "NavigationGrounding",
    "ObservationSnapshot",
    "ObservedEntity",
    "PlanIR",
    "PlanSketch",
    "PlanSketchGoal",
    "PlanSketchStep",
    "PlanStep",
    "PlanValidationError",
    "PlanValidator",
    "ReportDisposition",
    "ResourceLease",
    "ResourceLocks",
    "RobotStateSnapshot",
    "SafetyStateSnapshot",
    "SemanticRuntimeState",
    "SemanticTaskRuntimeAdapter",
    "SensorSnapshot",
    "SkillContract",
    "SkillContractRegistry",
    "SuccessCondition",
    "TaskExecutive",
    "TaskStateSnapshot",
    "ValidatedPlan",
    "ValidatedStep",
    "VerifiedFact",
    "admitted_plan_schema",
    "admitted_plan_sketch_schema",
    "bind_plan_context",
    "compile_plan_contracts",
    "compile_plan_sketch",
    "contextual_plan_schema",
    "contextual_planner_schema",
    "dispatch_key",
    "materialize_planner_output",
    "planner_output_contract",
]
