"""The dog's own map — online, object-centric semantic memory (card C-2).

Places the robot *saw*, kept across sessions, with the evidence that earned them
still attached. See :mod:`parcel_robot.online_map.online_map` for the
architecture and :mod:`parcel_robot.online_map.hygiene` for the safety gates.

Not to be confused with :mod:`parcel_robot.navigation.semantic_map`, which is
the sidecar-backed consumer-side candidate source that C-3 owns.
"""

from __future__ import annotations

from .entries import (
    CHANNEL_DETECTOR_LABEL,
    CHANNEL_EMBEDDING,
    CHANNEL_TEXT_NAME,
    DECAY_MARK_AFTER_MISSES,
    ENV_MAP_PATH,
    MAP_SCHEMA,
    MAX_ENTRIES,
    MAX_THUMBNAIL_BYTES,
    MIGRATABLE_SCHEMAS,
    NAME_DETECTOR_LABEL,
    NAME_PROMOTED,
    NAME_PROMOTION_VISITS,
    NAME_VLM_PROPOSED,
    ORIGIN_UNKNOWN,
    ORIGIN_VALUES,
    RETRIEVABLE_STATUSES,
    STATUS_ACTIVE,
    STATUS_DECAYED,
    STATUS_QUARANTINED,
    EmbeddingStamp,
    EvidenceOrigin,
    MapEntry,
    MapObservation,
    ProposedName,
    WriterProvenance,
    label_tokens,
    normalize_label,
    normalize_origin,
    origins_conflict,
)
from .hygiene import (
    NOTE_OK,
    NOTE_PLANAR,
    NOTE_RELIEF_UNVERIFIED,
    NOTE_TOO_LARGE,
    NOTE_TOO_SMALL,
    NOTE_VOLATILE,
    SIZE_PRIORS,
    HygieneVerdict,
    SizePrior,
    is_volatile_label,
    metric_extents,
    prior_for,
    relief_from_depth_patch,
    screen_observation,
)
from .ingest import (
    default_focal_lengths,
    embedding_stamp_from_record,
    map_freshness_report,
    observation_from_record,
    observations_from_frame,
)
from .online_map import (
    DEFAULT_FUSE_RADIUS_M,
    DEFAULT_VISIBILITY_RANGE_M,
    EMBEDDING_RERANKED,
    EMBEDDING_UNAVAILABLE_ABSENT,
    EMBEDDING_UNAVAILABLE_VERSION,
    EMBEDDING_UNUSED,
    IngestOutcome,
    MapCandidate,
    MapQueryResult,
    MapRefused,
    OnlineSemanticMap,
    cosine,
)
from .store import MapStoreRefused, OnlineMapStore, resolve_map_store_path

__all__ = [
    "CHANNEL_DETECTOR_LABEL",
    "CHANNEL_EMBEDDING",
    "CHANNEL_TEXT_NAME",
    "DECAY_MARK_AFTER_MISSES",
    "DEFAULT_FUSE_RADIUS_M",
    "DEFAULT_VISIBILITY_RANGE_M",
    "EMBEDDING_RERANKED",
    "EMBEDDING_UNAVAILABLE_ABSENT",
    "EMBEDDING_UNAVAILABLE_VERSION",
    "EMBEDDING_UNUSED",
    "ENV_MAP_PATH",
    "MAP_SCHEMA",
    "MAX_ENTRIES",
    "MAX_THUMBNAIL_BYTES",
    "MIGRATABLE_SCHEMAS",
    "NAME_DETECTOR_LABEL",
    "NAME_PROMOTED",
    "NAME_PROMOTION_VISITS",
    "NAME_VLM_PROPOSED",
    "NOTE_OK",
    "NOTE_PLANAR",
    "NOTE_RELIEF_UNVERIFIED",
    "NOTE_TOO_LARGE",
    "NOTE_TOO_SMALL",
    "NOTE_VOLATILE",
    "ORIGIN_UNKNOWN",
    "ORIGIN_VALUES",
    "RETRIEVABLE_STATUSES",
    "SIZE_PRIORS",
    "STATUS_ACTIVE",
    "STATUS_DECAYED",
    "STATUS_QUARANTINED",
    "EmbeddingStamp",
    "EvidenceOrigin",
    "HygieneVerdict",
    "IngestOutcome",
    "MapCandidate",
    "MapEntry",
    "MapObservation",
    "MapQueryResult",
    "MapRefused",
    "MapStoreRefused",
    "OnlineMapStore",
    "OnlineSemanticMap",
    "ProposedName",
    "SizePrior",
    "WriterProvenance",
    "cosine",
    "default_focal_lengths",
    "embedding_stamp_from_record",
    "is_volatile_label",
    "label_tokens",
    "map_freshness_report",
    "metric_extents",
    "normalize_label",
    "normalize_origin",
    "observation_from_record",
    "observations_from_frame",
    "origins_conflict",
    "prior_for",
    "relief_from_depth_patch",
    "resolve_map_store_path",
    "screen_observation",
]
