"""Pure versioned contracts for Parcel cross-track seams (K1).

No ROS, runtime, or agent wiring. Consumers import DTOs and freshness helpers
only; Opus owns later integration into ``runtime.py`` / ``agent.py``.
"""

from parcel_robot.contracts.freshness import (
    DEFAULT_DETECTION_TTL_NS,
    DEFAULT_DIALOGUE_STATE_TTL_NS,
    DEFAULT_SEMANTIC_TTL_NS,
    DEFAULT_SOCIAL_CUE_TTL_NS,
    DEFAULT_TRACK_TTL_NS,
    FreshnessVerdict,
    age_ns,
    check_freshness,
    detect_clock_jump,
    expires_from_ttl,
    is_expired,
    require_fresh,
    speed_cap_from_staleness_m_s,
)
from parcel_robot.contracts.v1 import (
    SCHEMA_VERSION,
    CovarianceND,
    DetectionMsg,
    DialogueActV1,
    DialogueClaimV1,
    DialogueStateMsg,
    DynamicTrackV1,
    EvidenceEnvelopeV1,
    GeometryV1,
    GoalRegionV1,
    OwnerTrackV1,
    PoseXYZYaw,
    PredictedOccupancyV1,
    ReactionProposalV1,
    SceneQueryV1,
    SemanticRegionV1,
    SkillFeedbackV1,
    SocialCueV1,
    identity_covariance,
)

__all__ = [
    "DEFAULT_DETECTION_TTL_NS",
    "DEFAULT_DIALOGUE_STATE_TTL_NS",
    "DEFAULT_SEMANTIC_TTL_NS",
    "DEFAULT_SOCIAL_CUE_TTL_NS",
    "DEFAULT_TRACK_TTL_NS",
    "SCHEMA_VERSION",
    "CovarianceND",
    "DetectionMsg",
    "DialogueActV1",
    "DialogueClaimV1",
    "DialogueStateMsg",
    "DynamicTrackV1",
    "EvidenceEnvelopeV1",
    "FreshnessVerdict",
    "GeometryV1",
    "GoalRegionV1",
    "OwnerTrackV1",
    "PoseXYZYaw",
    "PredictedOccupancyV1",
    "ReactionProposalV1",
    "SceneQueryV1",
    "SemanticRegionV1",
    "SkillFeedbackV1",
    "SocialCueV1",
    "age_ns",
    "check_freshness",
    "detect_clock_jump",
    "expires_from_ttl",
    "identity_covariance",
    "is_expired",
    "require_fresh",
    "speed_cap_from_staleness_m_s",
]
