#!/usr/bin/env python3
"""Sync repo ``configs/`` + ``prompts/`` into the packaged runtime_assets tree.

Run from the repository root after changing skills/navigation/prompt assets::

    .parcel/bin/python tools/sync_runtime_assets.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "src" / "parcel_robot" / "runtime_assets"
PACKAGE_CONFIG = REPO / "src" / "parcel_robot" / "config" / "robot.yaml"

# Curated subset required for headless/CI authority-loop smoke (not experiments).
NAV_FILES = (
    "default.yaml",
    "cities/demo_pois.yaml",
    "models/grid.yaml",
    "models/stub.yaml",
)


def _copy_tree(src: Path, dst: Path) -> int:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return sum(1 for p in dst.rglob("*") if p.is_file())


def main() -> int:
    if not (REPO / "configs").is_dir() or not (REPO / "prompts").is_dir():
        print("error: run from a Parcel checkout with configs/ and prompts/", file=sys.stderr)
        return 2

    DEST.mkdir(parents=True, exist_ok=True)

    skills_count = _copy_tree(REPO / "configs" / "skills", DEST / "configs" / "skills")
    prompts_count = _copy_tree(REPO / "prompts", DEST / "prompts")

    nav_dest = DEST / "configs" / "navigation"
    if nav_dest.exists():
        shutil.rmtree(nav_dest)
    copied_nav = 0
    for relative in NAV_FILES:
        src = REPO / "configs" / "navigation" / relative
        if not src.is_file():
            print(f"error: missing {src}", file=sys.stderr)
            return 2
        target = nav_dest / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
        copied_nav += 1

    shutil.copy2(REPO / "configs" / "robot.yaml", DEST / "configs" / "robot.yaml")
    # Keep the in-package fallback aligned with the canonical robot config so
    # legacy `FALLBACK_CONFIG` paths stop rejecting current speech keys.
    PACKAGE_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(REPO / "configs" / "robot.yaml", PACKAGE_CONFIG)

    marker = DEST / "README.md"
    marker.write_text(
        "# Packaged runtime assets\n\n"
        "Generated by `tools/sync_runtime_assets.py`. Do not edit by hand;\n"
        "edit repo-root `configs/` / `prompts/` and re-sync.\n"
        "MuJoCo meshes under `third_party/` are **not** packaged here.\n",
        encoding="utf-8",
    )

    print(
        f"synced runtime_assets: skills={skills_count} prompts={prompts_count} "
        f"nav={copied_nav} + robot.yaml → package fallback"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
